### PR TITLE
Zabbix 6.0 update (#2)

### PR DESCRIPTION
**Pull request by kodiakastu**
Updated template to zabbix 6.4, updated readme to reflect changes and now includes modified default template "Generic by SNMP" to resove #15.

### CODE REVIEW

**Comment by andymarden** [comment]
Can confirm this works on Zabbix 6.4 for Edgerouter 12p target

**Comment by kodiakastu** [comment]
Thanks I will update the readme!

**Comment by albin-lindstrom** [comment]
Resolves #15.

**Comment by notfixingit3** [comment]
Confirmed working on ER-4 and ER-Pro

**Comment by kodiakastu** [comment]
@albin-lindstrom Why was i closed an not merged ?
@notfixingit3 Will update the readme with this on the next cycle :)

**Comment by albin-lindstrom** [comment]
> @albin-lindstrom Why was i closed and not merged ?
> @notfixingit3 Will update the readme with this on the next cycle :)

Sorry my bad, my tipsy ass hit the wrong button yesterday.

**Comment by kodiakastu** [comment]
> > @albin-lindstrom Why was i closed and not merged ?
> > @notfixingit3 Will update the readme with this on the next cycle :)
> 
> Sorry my bad, my tipsy ass hit the wrong button yesterday.

Haha no problems! Was just wondering 😉

**Pull request merged**
